### ISSUE TITLE
TDT triples does not go well with TDT 5.6

### ISSUE THREAD

**Issue by laurensdv** [tdt/triples#51]
tdt triples installation 'works' but breaks the tdt installation in version 5.6: the resolving of dataset.(filetype) does not work only the html version remains available.

Also the label in the navbar is strange tdt/triples::admin_menu

The public assets (triples.min) does not get automatically copied to the public folder.

furthermore the dependencies are broken, which I tried to fix but some more changes are required to make it integrate (in composer.json):

        "php": ">=5.3.0",
        "illuminate/support": "4.2.0", instead of 4.1.*
        "semsol/arc2" : "dev-master",
        "easyrdf/easyrdf" : "0.9.1", instead of dev-master

could you check this?

**Comment by coreation** [comment]
Hey @laurensdv I'll see what's going wrong, for the assets you'll have to publish them through a publish command: php artisan asset:publish tdt/triples

**Comment by coreation** [comment]
https://github.com/tdt/triples/commit/239509e453cb88cce7036da6dca81a1545a4ba48

**Comment by coreation** [comment]
@laurensdv the fix has been merged with master, take not though, the php requirement is now 5.4, to make it compatible with 5.12.

**Comment by laurensdv** [comment]
Hi @coreation, switched to PHP 5.4, still get the illuminate/support issue when including tdt/triples in the composer.json:

   Your requirements could not be resolved to an installable set of packages.

   Problem 1
    - don't install illuminate/support v4.2.1|don't install laravel/framework v4.2.0
    - don't install illuminate/support v4.2.1|remove laravel/framework v4.2.0
    - tdt/triples dev-master requires illuminate/support 4.2.1 -> satisfiable by illuminate/support[v4.2.1].
    - Installation request for tdt/triples dev-master -> satisfiable by tdt/triples[dev-master].
    - Installation request for laravel/framework 4.2.0 -> satisfiable by laravel/framework[v4.2.0].

**Comment by laurensdv** [comment]
I extended this composer.json: https://github.com/tdt/core/blob/master/composer.json with "tdt/triples": "dev-master".

**Comment by laurensdv** [comment]
Resolved by changing to 4.2.1 in composer.json.

However issue with the 404 on json version of e.g. csv files remains:

    [2016-01-25 09:04:32] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'No property (target_group_categories.json) has been found.' in /home/xblue/tdt_tourism/bootstrap/compiled.php:759
Stack trace:
    #0 /home/xblue/tdt_tourism/bootstrap/compiled.php(3261): Illuminate\Foundation\Application->abort(404, 'No property (ta...')
    #1 /home/xblue/tdt_tourism/app/Tdt/Core/Datasets/DatasetController.php(293): Illuminate\Support\Facades\Facade::__callStatic('abort', Array)
    #2 /home/xblue/tdt_tourism/app/Tdt/Core/Datasets/DatasetController.php(293): Illuminate\Support\Facades\App::abort(404, 'No property (ta...')
    #3 /home/xblue/tdt_tourism/app/Tdt/Core/Datasets/DatasetController.php(336): Tdt\Core\Datasets\DatasetController::applyRestFilter(Array, Array)
    #4 /home/xblue/tdt_tourism/vendor/tdt/triples/src/Tdt/Triples/Controllers/DataController.php(52): Tdt\Core\Datasets\DatasetController::fetchData('references/targ...')
    #5 [internal function]: Tdt\Triples\Controllers\DataController->resolve('references/targ...')
    #6 /home/xblue/tdt_tourism/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
    #7 /home/xblue/tdt_tourism/bootstrap/compiled.php(5585): Illuminate\Routing\Controller->callAction('resolve', Array)
    #8 /home/xblue/tdt_tourism/bootstrap/compiled.php(5573): Illuminate\Routing\ControllerDispatcher->call(Object(Tdt\Triples\Controllers\DataController), Object(Illuminate\Routing\Route), 'resolve')
    #9 /home/xblue/tdt_tourism/bootstrap/compiled.php(4804): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Tdt\\Triples\\Con...', 'resolve')
    #10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('references/targ...')
    #11 /home/xblue/tdt_tourism/bootstrap/compiled.php(5132): call_user_func_array(Object(Closure), Array)
    #12 /home/xblue/tdt_tourism/bootstrap/compiled.php(4829): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
    #13 /home/xblue/tdt_tourism/bootstrap/compiled.php(4817): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
    #14 /home/xblue/tdt_tourism/bootstrap/compiled.php(706): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
    #15 /home/xblue/tdt_tourism/bootstrap/compiled.php(687): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
    #16 /home/xblue/tdt_tourism/bootstrap/compiled.php(7459): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
    #17 /home/xblue/tdt_tourism/bootstrap/compiled.php(8065): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
    #18 /home/xblue/tdt_tourism/bootstrap/compiled.php(8012): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
    #19 /home/xblue/tdt_tourism/bootstrap/compiled.php(10881): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
    #20 /home/xblue/tdt_tourism/bootstrap/compiled.php(648): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
    #21 /home/xblue/tdt_tourism/public/index.php(49): Illuminate\Foundation\Application->run()
    #22 {main} [] []

**Comment by coreation** [comment]
What URI did you try to retrieve?

**Comment by laurensdv** [comment]
http://lddemo.mmlab.be/tourism/references/target_group_categories.json

**Comment by laurensdv** [comment]
Note that http://lddemo.mmlab.be/tourism/references/target_group_categories works and that this json  URI worked before I added tdt/triples.

**Comment by coreation** [comment]
I'll take a look and see what pops up, the version can indeed by updated without any harm. I think the triples routes regular expression is a bit too greedy.
